baseurl: '/'
permalink: pretty
title: 'Jekyll Serif'

logo:
  mobile: "images/logo/logo-icon.png"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/logo-icon.png"
  desktop_height: "60px"
  desktop_width: "60px"

home: 
  limit_services: 6

collections:
  services:
    output: true
    sort_by: weight

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"

sass:
  style: compressed # possible values: nested expanded compact compressed
  quiet_deps: true
  sourcemap: never

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
  - .git
  - _config.yml
